version: '3.4'
services:
  linuxgsm:
    build: 
      context: .
      dockerfile: pz.Dockerfile
    container_name: pzserver
    environment:
      - GAMESERVER=pzserver
      - LGSM_GITHUBUSER=GameServerManagers
      - LGSM_GITHUBREPO=LinuxGSM
      - LGSM_GITHUBBRANCH=master
    volumes:
      - /home/docker/linuxgsm/pzserver/serverfiles:/home/linuxgsm/serverfiles
      - /home/docker/linuxgsm/pzserver/log:/home/linuxgsm/log
      - /home/docker/linuxgsm/pzserver/config-lgsm:/home/linuxgsm/lgsm/config-lgsm
    ports:
      - "16261:16261/udp"
    restart: unless-stopped
